version: '2'

services:
  api:
    build: .
    ports:
      - 8000:8000
  yolov7:
    build: ./yolov7
    ports:
      - 8001:8001
  yolov6r1:
    build: ./yolov6r1
    ports:
      - 8002:8002
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - yolov7
      - yolov6r1
    volumes:
      - ./log:/log:z
      - /etc/letsencrypt/live/tools.luxonis.com/privkey.pem:/ssl/key.pem
      - /etc/letsencrypt/live/tools.luxonis.com/fullchain.pem:/ssl/cert.pem
